services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

    environment:
      TZ: Europe/Moscow
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_DEFAULT_VHOST: vhost

    ports:
      - "5672:5672"
      - "15672:15672"
